### ISSUE TITLE
Changing format of code markdown

### ISSUE THREAD

**Issue by mandyWW** [buggyrace/buggy-race-server#220]
The current view of code markdown makes the text quite hard to read / distinguish from "normal" text. Could we instead have something more akin to how `GitHub` shows it ie. as highlighted text.

**Comment by mandyWW** [comment]
Also the current text appears quite spaced out:

![image](https://github.com/buggyrace/buggy-race-server/assets/1316724/04b1d6dc-18ce-48fb-b36b-b5bc2f8270a8)

**Comment by davewhiteland** [comment]
This is in task list — need to add `background-color` as well as changing colour.

Can't change monospace spacing, but maybe switch to a font (Source Sans Code?) that's a little less stark (I think the minimal "t" isn't helping there).


Example on the docs site seems to be handling inline code quite nicely:

![Screenshot 2024-05-01 at 08 43 40](https://github.com/buggyrace/buggy-race-server/assets/111320/c2a4f696-4c92-406b-89ef-39ca9bf3d41e)

**Comment by davewhiteland** [comment]
d89d389  Added pale background, a wee nip o' padding, and a border, now looks like this (didn't change the font, that's a bigger jump for now).

![Screenshot 2024-05-04 at 14 28 17](https://github.com/buggyrace/buggy-race-server/assets/111320/461cfaf2-8d55-4809-9672-f68383c6e6c0)
