### ISSUE TITLE
Demo buggy race server

### ISSUE THREAD

**Issue by KuipersT** [buggyrace/buggy-race-server#27]
I think we can be generous and allow for a demo buggy race server, open for general registration on the main page to allow people to get a feel for how it works. This would just require some adaptations to the configs but we could run https://demo.buggyrace.net.

We are already deploying to a dev environment, so in the end it makes sense to move this over to a fully functional (or partly mock-up, i.e. admin features) demo environment.

**Comment by davewhiteland** [comment]
Done on https://demo.buggyrace.net (currently on Herku, running off `main`)

Starting to drop links to it into the documentation over on buggy-race-about too, yay
